
import os
import pickle
import chromadb
from rank_bm25 import BM25Okapi
from core.config import CHROMA_DB_DIR, BM25_INDEX_PATH
from ingestion.embedder import BGEEmbedder

PARENT_MAP_PATH = os.path.join(CHROMA_DB_DIR, "parent_chunks_map.pkl")

class DocumentIndexer:
    def __init__(self):
        self.chroma_client = chromadb.PersistentClient(path=CHROMA_DB_DIR)
        self.collection = self.chroma_client.get_or_create_collection(
            name="arxiv_papers_collection"
        )
        self.embedder = BGEEmbedder()

    def _tokenize_text(self, text: str) -> list[str]:
        return text.lower().split()

    def index_hierarchical_data(self, parents: list[dict], children: list[dict]):
        """
        Indexes child chunks into ChromaDB & BM25, and saves parent lookup references.
        Accepts the flat lists generated by your updated chunker.
        """
        if not children:
            print("No child chunks provided for indexing.")
            return

        # 1. Build and serialize the Parent Registry Map
        print(f"\n--- Processing {len(parents)} Parent Contexts ---")
        parent_lookup_registry = {}
        for p in parents:
            parent_lookup_registry[p["parent_id"]] = p["text"]
            
        os.makedirs(CHROMA_DB_DIR, exist_ok=True)
        with open(PARENT_MAP_PATH, "wb") as f:
            pickle.dump(parent_lookup_registry, f)
        print("✅ Parent lookup registry map saved to disk.")

        # 2. Extract arrays required by vector and keyword collections
        child_ids = []
        child_texts = []
        child_metadatas = []
        
        for idx, child in enumerate(children):
            # Formulate a structured unique ID for Chroma/BM25 using your chunk metadata
            meta = child["metadata"]
            unique_id = f"{meta['source']}_S{meta['section_id']}_P{meta['parent_id'].split('_P')[-1]}_C{meta['chunk_id']}"
            
            child_ids.append(unique_id)
            child_texts.append(child["text"])
            child_metadatas.append(meta)

        print(f"--- Indexing {len(child_ids)} High-Fidelity Child Chunks ---")

        # 3. Dense Indexing: ChromaDB
        print("Generating BGE embeddings for all child chunks...")
        embeddings = self.embedder.embed_batch(child_texts)
        
        print("Storing child vectors in ChromaDB...")
        self.collection.upsert(
            ids=child_ids,
            embeddings=embeddings,
            documents=child_texts,
            metadatas=child_metadatas
        )
        print("✅ ChromaDB dense index updated successfully.")

        # 4. Sparse Indexing: BM25
        print("Building BM25 sparse keyword index over child chunks...")
        tokenized_corpus = [self._tokenize_text(text) for text in child_texts]
        bm25 = BM25Okapi(tokenized_corpus)
        
        bm25_data = {
            "bm25_instance": bm25,
            "documents": child_texts,
            "metadatas": child_metadatas,
            "ids": child_ids
        }
        
        with open(BM25_INDEX_PATH, "wb") as f:
            pickle.dump(bm25_data, f)
            
        print("✅ BM25 sparse index updated successfully.")
        print(f"--- Ingestion Complete! Core DB Assets saved in: {CHROMA_DB_DIR} ---\n")